// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCws3SN2jxXmUwSJhmuW-Bg6r0y8pRUClI',
    appId: '1:923427125583:web:ae352c4e5b864d93266d3a',
    messagingSenderId: '923427125583',
    projectId: 'test-7dbab',
    authDomain: 'test-7dbab.firebaseapp.com',
    databaseURL: 'https://test-7dbab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-7dbab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjhUO1moLpg_FTnsSq5Qhu9ajIzm6ZLCI',
    appId: '1:923427125583:android:7bce409361fcaef4266d3a',
    messagingSenderId: '923427125583',
    projectId: 'test-7dbab',
    databaseURL: 'https://test-7dbab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-7dbab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfv32lYY2sbl869nGvYbBjcImSkKZlC90',
    appId: '1:923427125583:ios:d683ee24d4ba1f27266d3a',
    messagingSenderId: '923427125583',
    projectId: 'test-7dbab',
    databaseURL: 'https://test-7dbab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-7dbab.appspot.com',
    iosClientId: '923427125583-q1f7iuvcpp0sq48gnkm4q66rcg3ih57b.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfv32lYY2sbl869nGvYbBjcImSkKZlC90',
    appId: '1:923427125583:ios:d683ee24d4ba1f27266d3a',
    messagingSenderId: '923427125583',
    projectId: 'test-7dbab',
    databaseURL: 'https://test-7dbab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-7dbab.appspot.com',
    iosClientId: '923427125583-q1f7iuvcpp0sq48gnkm4q66rcg3ih57b.apps.googleusercontent.com',
    iosBundleId: 'com.example.social',
  );
}
